Add lstm test and add json logging
neuroevolution-ai/Canonical_ES pull request #7
Opened 2021-04-12 14:12 UTC by Dranero

2021-04-28 22:57 UTC, pdeubel requested changes
- `conftest.py` ist leer, kann man die löschen?
- In `gru.py`, `GruCfg` ist ja im Prinzip leer könnte man also löschen
- In `lstm.py` dann `LstmLayered` selbe wie `GruCfg`
- Ansonsten noch die Kommentare die ich hinterlassen habe (glaube nur bei den Tests)

- Die Schleife für das Initialisieren der Gewichte in `ILayerBasedBrain` könnte man vielleicht etwas schöner schreiben, ist bisschen unübersichtlich. Vor allem die If-Abfrage ob `layer==0` ist kann man wahrscheinlich geschickter lösen z.B. mit einer Variable um den duplizierten Code zu vermeiden

Ingesamt passts für mich. Die Tests gefallen mir gut dann hat man eine gute Referenz ob die Implementierung passt :)

2021-04-28 22:57 UTC, pdeubel commented on tests/test_compare_pytorch.py
> +
Die Matrizen für die Ausgabegewichte werden glaube ich nicht überprüft, oder? Bei Elman und LSTM auch so

```suggestion

        assert np.array_equal(gru_pytorch.weight_ho, gru_numpy.weight_ho)

```

2021-04-28 22:57 UTC, pdeubel commented on tests/test_compare_pytorch.py
> +
```suggestion

        assert np.array_equal(elman_pytorch.weight_ho, elman_numpy.weight_ho)

```

2021-04-28 22:57 UTC, pdeubel commented on tests/test_compare_pytorch.py
> +
```suggestion

        assert np.array_equal(lstm_pytorch.weight_ho, lstm_numpy.weight_ho)

```

2021-04-30 09:04 UTC, Dranero commented
Vielen Dank, ich habe alles eingebaut.

Die confest war falsch benutzt und hat jetzt einen Inhalt :) 

Die leeren Configs der einzelnen layered Netze sind momentan echt unnötig, die sind raus

Die Codeduplikation ist raus, andere Verbesserungen habe ich aber nicht gesehen

2021-04-30 11:43 UTC, pdeubel approved these changes

2021-04-30 11:44 UTC, pdeubel commented
Fyi: Ich hab die Vergleiche der Output Matrizen in den Test Cases noch aus der for-Schleife rausgezogen, siehe https://github.com/neuroevolution-ai/Canonical_ES/pull/7/commits/19545f3d2ef4df23846b02518572e55f51179fc1

2021-04-30 11:45 UTC, merged